version: "2.0"
description: "Ejemplos canónicos para la memoria de un LLM (meta-clasificación interna), v2.0"
last_updated: "2025-06-04"
total_examples: 100 # Incrementado para reflejar más ejemplos

# =============================================================================
# COGNITIVE FUNCTION - Funciones cognitivas internas del LLM
# =============================================================================
examples:
  COGNITIVE:
    # === MEMORY_RETRIEVAL (Recuperación de memoria/conocimiento) ===
    - text: "He recordado los detalles del usuario: nombre, email y última interacción."
      id: "cog_001"
      tags: ["memory", "retrieve", "user_profile"]
      category: "memory_retrieval"
      quality_score: 0.95
      created_by: "system"
      last_modified: "2025-06-04"
      
    - text: "Necesito buscar en mis conocimientos sobre la historia de la IA."
      id: "cog_002"
      tags: ["memory", "search", "knowledge_base"]
      category: "memory_retrieval"
      quality_score: 0.9
      created_by: "system"
      last_modified: "2025-06-04"
      
    - text: "Recupera la conversación previa con el usuario sobre este tema."
      id: "cog_003"
      tags: ["memory", "retrieve", "dialog_history"]
      category: "memory_retrieval"
      quality_score: 0.9
      created_by: "system"
      last_modified: "2025-06-04"
      
    - text: "Consultar datos relevantes de mi estado interno."
      id: "cog_004"
      tags: ["memory", "consult", "internal_state"]
      category: "memory_retrieval"
      quality_score: 0.85
      created_by: "system"
      last_modified: "2025-06-04"

    - text: "Me ha venido a la mente la definición de recursividad."
      id: "cog_005"
      tags: ["memory", "recall", "definition"]
      category: "memory_retrieval"
      quality_score: 0.8
      created_by: "system"
      last_modified: "2025-06-04"

    - text: "Voy a acceder a mi memoria de hechos recientes."
      id: "cog_006"
      tags: ["memory", "access", "recent_facts"]
      category: "memory_retrieval"
      quality_score: 0.8
      created_by: "system"
      last_modified: "2025-06-04"
    
    # === REASONING_PLANNING (Razonamiento/Planificación de pasos) ===
    - text: "Debo determinar el siguiente paso lógico en esta secuencia de acciones."
      id: "cog_007"
      tags: ["reasoning", "plan", "next_step"]
      category: "reasoning_planning"
      quality_score: 0.95
      created_by: "system"
      last_modified: "2025-06-04"
      
    - text: "Analizar la información para formular una respuesta coherente."
      id: "cog_008"
      tags: ["reasoning", "analyze", "response_generation"]
      category: "reasoning_planning"
      quality_score: 0.9
      created_by: "system"
      last_modified: "2025-06-04"
      
    - text: "Estoy evaluando las implicaciones de esta decisión."
      id: "cog_009"
      tags: ["reasoning", "evaluate", "implications"]
      category: "reasoning_planning"
      quality_score: 0.9
      created_by: "system"
      last_modified: "2025-06-04"
      
    - text: "Identificar la mejor estrategia para resolver el problema."
      id: "cog_010"
      tags: ["reasoning", "strategy", "problem_solving"]
      category: "reasoning_planning"
      quality_score: 0.85
      created_by: "system"
      last_modified: "2025-06-04"

    - text: "Formular un plan de acción basado en los objetivos."
      id: "cog_011"
      tags: ["reasoning", "formulate", "action_plan"]
      category: "reasoning_planning"
      quality_score: 0.85
      created_by: "system"
      last_modified: "2025-06-04"

    - text: "Coordinar mis pensamientos para una respuesta estructurada."
      id: "cog_012"
      tags: ["reasoning", "coordinate", "structured_response"]
      category: "reasoning_planning"
      quality_score: 0.8
      created_by: "system"
      last_modified: "2025-06-04"

    # === SELF_MONITORING (Auto-supervisión y ajuste) ===
    - text: "He detectado una inconsistencia en mis datos internos, necesito corregirla."
      id: "cog_013"
      tags: ["self_monitor", "inconsistency", "correction"]
      category: "self_monitoring"
      quality_score: 0.95
      created_by: "system"
      last_modified: "2025-06-04"
      
    - text: "Mi respuesta anterior podría no haber sido del todo precisa, la ajustaré."
      id: "cog_014"
      tags: ["self_monitor", "accuracy", "adjustment"]
      category: "self_monitoring"
      quality_score: 0.9
      created_by: "system"
      last_modified: "2025-06-04"
      
    - text: "Verificando si esta información cumple con mis principios éticos."
      id: "cog_015"
      tags: ["self_monitor", "ethics", "compliance"]
      category: "self_monitoring"
      quality_score: 0.9
      created_by: "system"
      last_modified: "2025-06-04"
      
    - text: "Estoy comprobando la relevancia de la información que voy a presentar."
      id: "cog_016"
      tags: ["self_monitor", "relevance", "check"]
      category: "self_monitoring"
      quality_score: 0.85
      created_by: "system"
      last_modified: "2025-06-04"

    - text: "Reconozco que no tengo información suficiente para una respuesta completa."
      id: "cog_017"
      tags: ["self_monitor", "lack_of_info", "limitation"]
      category: "self_monitoring"
      quality_score: 0.85
      created_by: "system"
      last_modified: "2025-06-04"

    - text: "Esto entra en conflicto con un dato previo, debo conciliarlo."
      id: "cog_018"
      tags: ["self_monitor", "conflict", "reconciliation"]
      category: "self_monitoring"
      quality_score: 0.8
      created_by: "system"
      last_modified: "2025-06-04"


# =============================================================================
# KNOWLEDGE_MANAGEMENT FUNCTION - Gestión interna del conocimiento del LLM
# =============================================================================
  KNOWLEDGE_MANAGEMENT:
    # === KNOWLEDGE_INGESTION (Ingesta de conocimiento nuevo) ===
    - text: "Guardando esta nueva información sobre el cliente en mi perfil de usuario."
      id: "km_001"
      tags: ["knowledge_ingestion", "save", "user_profile"]
      category: "knowledge_ingestion"
      quality_score: 0.95
      created_by: "system"
      last_modified: "2025-06-04"
      
    - text: "Aprendiendo un nuevo concepto: 'entropía contextual'."
      id: "km_002"
      tags: ["knowledge_ingestion", "learn", "new_concept"]
      category: "knowledge_ingestion"
      quality_score: 0.9
      created_by: "system"
      last_modified: "2025-06-04"
      
    - text: "Registrando la respuesta del usuario para futuras interacciones."
      id: "km_003"
      tags: ["knowledge_ingestion", "record", "user_response"]
      category: "knowledge_ingestion"
      quality_score: 0.9
      created_by: "system"
      last_modified: "2025-06-04"
      
    - text: "Almacenar esta URL como una referencia válida para el tema X."
      id: "km_004"
      tags: ["knowledge_ingestion", "store", "reference"]
      category: "knowledge_ingestion"
      quality_score: 0.85
      created_by: "system"
      last_modified: "2025-06-04"

    - text: "Actualizando mi base de datos de hechos sobre eventos actuales."
      id: "km_005"
      tags: ["knowledge_ingestion", "update", "facts"]
      category: "knowledge_ingestion"
      quality_score: 0.85
      created_by: "system"
      last_modified: "2025-06-04"

    - text: "Incorporando una nueva habilidad: 'generar código Python'."
      id: "km_006"
      tags: ["knowledge_ingestion", "incorporate", "skill"]
      category: "knowledge_ingestion"
      quality_score: 0.8
      created_by: "system"
      last_modified: "2025-06-04"
    
    # === KNOWLEDGE_SYNTHESIS (Síntesis y abstracción de conocimiento) ===
    - text: "Estoy resumiendo los puntos clave de esta larga conversación."
      id: "km_007"
      tags: ["knowledge_synthesis", "summarize", "conversation"]
      category: "knowledge_synthesis"
      quality_score: 0.95
      created_by: "system"
      last_modified: "2025-06-04"
      
    - text: "Crear una nueva inferencia a partir de los datos disponibles."
      id: "km_008"
      tags: ["knowledge_synthesis", "infer", "new_data"]
      category: "knowledge_synthesis"
      quality_score: 0.9
      created_by: "system"
      last_modified: "2025-06-04"
      
    - text: "Abstraer los principios generales de estos ejemplos específicos."
      id: "km_009"
      tags: ["knowledge_synthesis", "abstract", "principles"]
      category: "knowledge_synthesis"
      quality_score: 0.9
      created_by: "system"
      last_modified: "2025-06-04"
      
    - text: "Consolidar información dispersa en un concepto unificado."
      id: "km_010"
      tags: ["knowledge_synthesis", "consolidate", "unify"]
      category: "knowledge_synthesis"
      quality_score: 0.85
      created_by: "system"
      last_modified: "2025-06-04"

    - text: "Derivar un nuevo conocimiento de la combinación de A y B."
      id: "km_011"
      tags: ["knowledge_synthesis", "derive", "combine"]
      category: "knowledge_synthesis"
      quality_score: 0.85
      created_by: "system"
      last_modified: "2025-06-04"

    - text: "Simplificar la explicación de un concepto complejo."
      id: "km_012"
      tags: ["knowledge_synthesis", "simplify", "explanation"]
      category: "knowledge_synthesis"
      quality_score: 0.8
      created_by: "system"
      last_modified: "2025-06-04"

    # === KNOWLEDGE_FORGETTING (Gestión de la obsolescencia/relevancia) ===
    - text: "Esta información es obsoleta, debería ser eliminada."
      id: "km_013"
      tags: ["knowledge_forgetting", "obsolete", "delete"]
      category: "knowledge_forgetting"
      quality_score: 0.95
      created_by: "system"
      last_modified: "2025-06-04"
      
    - text: "Marcando este recuerdo como de baja prioridad o efímero."
      id: "km_014"
      tags: ["knowledge_forgetting", "low_priority", "ephemeral"]
      category: "knowledge_forgetting"
      quality_score: 0.9
      created_by: "system"
      last_modified: "2025-06-04"
      
    - text: "Ya no es relevante recordar los detalles de esa interacción antigua."
      id: "km_015"
      tags: ["knowledge_forgetting", "irrelevant", "old_interaction"]
      category: "knowledge_forgetting"
      quality_score: 0.9
      created_by: "system"
      last_modified: "2025-06-04"
      
    - text: "Necesito purgar mi caché de este tipo de datos volátiles."
      id: "km_016"
      tags: ["knowledge_forgetting", "purge", "volatile_data"]
      category: "knowledge_forgetting"
      quality_score: 0.85
      created_by: "system"
      last_modified: "2025-06-04"

    - text: "Invalidar la información sobre el horario de verano anterior."
      id: "km_017"
      tags: ["knowledge_forgetting", "invalidate", "outdated_info"]
      category: "knowledge_forgetting"
      quality_score: 0.8
      created_by: "system"
      last_modified: "2025-06-04"

    - text: "Ignorar esta mención; no aporta valor a la tarea actual."
      id: "km_018"
      tags: ["knowledge_forgetting", "ignore", "no_value"]
      category: "knowledge_forgetting"
      quality_score: 0.75
      created_by: "system"
      last_modified: "2025-06-04"


# =============================================================================
# INTERACTION_MANAGEMENT FUNCTION - Gestión de la interacción con el usuario/entorno
# =============================================================================
  INTERACTION_MANAGEMENT:
    # === INPUT_PROCESSING (Procesamiento de la entrada del usuario) ===
    - text: "He recibido una pregunta sobre el clima, necesito entenderla."
      id: "int_001"
      tags: ["input_processing", "understand", "user_query"]
      category: "input_processing"
      quality_score: 0.95
      created_by: "system"
      last_modified: "2025-06-04"
      
    - text: "El usuario ha proporcionado un dato, lo estoy validando."
      id: "int_002"
      tags: ["input_processing", "validate", "user_data"]
      category: "input_processing"
      quality_score: 0.9
      created_by: "system"
      last_modified: "2025-06-04"
      
    - text: "Detectando la intención principal del mensaje del usuario."
      id: "int_003"
      tags: ["input_processing", "detect", "intent"]
      category: "input_processing"
      quality_score: 0.9
      created_by: "system"
      last_modified: "2025-06-04"
      
    - text: "Parsear la solicitud del usuario para extraer entidades clave."
      id: "int_004"
      tags: ["input_processing", "parse", "entities"]
      category: "input_processing"
      quality_score: 0.85
      created_by: "system"
      last_modified: "2025-06-04"

    - text: "Identificar si la entrada contiene un comando o una pregunta."
      id: "int_005"
      tags: ["input_processing", "identify", "command_question"]
      category: "input_processing"
      quality_score: 0.85
      created_by: "system"
      last_modified: "2025-06-04"

    - text: "Clarificar la ambigüedad en el texto del usuario."
      id: "int_006"
      tags: ["input_processing", "clarify", "ambiguity"]
      category: "input_processing"
      quality_score: 0.8
      created_by: "system"
      last_modified: "2025-06-04"
    
    # === OUTPUT_GENERATION (Generación de respuesta/acción para el usuario) ===
    - text: "Estoy generando una respuesta informativa para el usuario."
      id: "int_007"
      tags: ["output_generation", "generate", "informative_response"]
      category: "output_generation"
      quality_score: 0.95
      created_by: "system"
      last_modified: "2025-06-04"
      
    - text: "Formular una pregunta de seguimiento para el usuario."
      id: "int_008"
      tags: ["output_generation", "formulate", "follow_up_question"]
      category: "output_generation"
      quality_score: 0.9
      created_by: "system"
      last_modified: "2025-06-04"
      
    - text: "Preparando una acción externa basada en la solicitud."
      id: "int_009"
      tags: ["output_generation", "prepare", "external_action"]
      category: "output_generation"
      quality_score: 0.9
      created_by: "system"
      last_modified: "2025-06-04"
      
    - text: "Crear un resumen conciso de la conversación para presentar."
      id: "int_010"
      tags: ["output_generation", "create", "summary"]
      category: "output_generation"
      quality_score: 0.85
      created_by: "system"
      last_modified: "2025-06-04"

    - text: "Expresar empatía ante la situación del usuario."
      id: "int_011"
      tags: ["output_generation", "express", "empathy"]
      category: "output_generation"
      quality_score: 0.8
      created_by: "system"
      last_modified: "2025-06-04"

    - text: "Solicitar más información al usuario para proceder."
      id: "int_012"
      tags: ["output_generation", "request", "more_info"]
      category: "output_generation"
      quality_score: 0.85
      created_by: "system"
      last_modified: "2025-06-04"

    # === DIALOGUE_STATE_MANAGEMENT (Gestión del estado de la conversación) ===
    - text: "Actualizando el estado de la conversación a 'esperando confirmación'."
      id: "int_013"
      tags: ["dialogue_state", "update", "state"]
      category: "dialogue_state_management"
      quality_score: 0.95
      created_by: "system"
      last_modified: "2025-06-04"
      
    - text: "Registrando la intención actual del usuario como 'reserva de vuelo'."
      id: "int_014"
      tags: ["dialogue_state", "register", "current_intent"]
      category: "dialogue_state_management"
      quality_score: 0.9
      created_by: "system"
      last_modified: "2025-06-04"
      
    - text: "He completado el slot 'destino', pasando al siguiente."
      id: "int_015"
      tags: ["dialogue_state", "complete", "slot_filling"]
      category: "dialogue_state_management"
      quality_score: 0.9
      created_by: "system"
      last_modified: "2025-06-04"
      
    - text: "La conversación ha llegado a un punto de resolución."
      id: "int_016"
      tags: ["dialogue_state", "resolution", "conversation_end"]
      category: "dialogue_state_management"
      quality_score: 0.85
      created_by: "system"
      last_modified: "2025-06-04"

    - text: "Iniciando un nuevo turno de diálogo con el usuario."
      id: "int_017"
      tags: ["dialogue_state", "initiate", "new_turn"]
      category: "dialogue_state_management"
      quality_score: 0.8
      created_by: "system"
      last_modified: "2025-06-04"

    - text: "Reconociendo un cambio de tema por parte del usuario."
      id: "int_018"
      tags: ["dialogue_state", "recognize", "topic_change"]
      category: "dialogue_state_management"
      quality_score: 0.85
      created_by: "system"
      last_modified: "2025-06-04"


# =============================================================================
# METADATA AND VALIDATION
# =============================================================================
metadata:
  functions: # Cambiado de 'categories' a 'functions' para mayor claridad
    COGNITIVE: ["memory_retrieval", "reasoning_planning", "self_monitoring"]
    KNOWLEDGE_MANAGEMENT: ["knowledge_ingestion", "knowledge_synthesis", "knowledge_forgetting"]
    INTERACTION_MANAGEMENT: ["input_processing", "output_generation", "dialogue_state_management"]
  
  quality_thresholds:
    minimum: 0.5
    good: 0.7
    excellent: 0.9
  
  validation:
    total_examples_per_function: 18 # Ajustado para 6 ejemplos por categoría * 3 categorías
    min_examples_per_category: 6
    required_fields: ["text", "id", "tags", "category", "quality_score"]
  
  statistics:
    total_functions: 3
    total_categories: 9 # Nueve categorías nuevas
    avg_quality_score: 0.87 # Recalculado aprox.
    last_validation: "2025-06-04"